name: second_workflow
on: [push, workflow_dispatch]
jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3.5.3 #run is not used in case of action
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - name: run py file
        run: python3 ./Hello.py
  
  myjob2:
    needs: [myjob1] #needs keyword makes this sequential
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3.5.3 #run is not used in case of action
      - name: run py file
        run: python3 ./timenow.py
  
  myjob3:
    needs: [myjob2] #needs keyword makes this sequential
    runs-on: ubuntu-latest
    steps:
      - name: Output Context
        run: echo "${{toJSON(github)}}" #https://docs.github.com/en/actions/learn-github-actions/contexts

          
